export const ADD_ACTIVE_TODO = "ADD_ACTIVE_TODO";
export const REMOVE_ACTIVE_TODO = "REMOVE_ACTIVE_TODO";
export const ADD_COMPLTED_TODO = "ADD_COMPLTED_TODO";
export const REMOVE_COMPLETED_TODO = "REMOVE_COMPLETED_TODO";
